#!/usr/bin/python3
"""Factorize as many numbers as possible
into a product of two smaller numbers.
"""
import sys


def factorize_number(n):
	factors = []
	for i in range(2, int(n ** 0.5) + 1):
		while n % i == 0:
			factors.append((i, n // i))
			n //= i
	if n > 1:
		factors.append((n, 1))
	return factors


def main():
	if len(sys.argv) != 2:
		print("Usage: factors <file>")
		sys.exit(1)

	input_file = sys.argv[1]

	try:
		with open(input_file, 'r') as f:
			numbers = [int(line.strip()) for line in f]

		with open("output.txt", 'w') as f:
			for num in numbers:
				factorizations = factorize_number(num)
				for factorization in factorizations:
					p, q = factorization
					f.write("{} = {} * {}\n".format(num, p, q))

		print("Factorizations completed. Results written to output.txt")

	except FileNotFoundError:
		print("File not found.")
	except ValueError:
		print("Invalid input in the file. Please ensure all lines contain valid natural numbers greater than 1.")


if __name__ == "__main__":
	main()

